name: CI

on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - run: nix-shell -p ghc --run "ghc -Wall -Werror Main.hs"
